workflows:
  ios-release:
    name: iOS Release Build

    environment:
      flutter: stable
      xcode: latest

    ios_signing:
      distribution_type: app_store
      bundle_identifier: com.acaxochi.turismo

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build IPA
        script: flutter build ipa

    artifacts:
      - build/ios/ipa/*.ipa