workflows:
  ios-release:
    name: iOS IPA Release

    max_build_duration: 60

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: stable
      xcode: latest

      vars:
        BUNDLE_ID: "com.acaxochi.turismo"

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.acaxochi.turismo

    scripts:
      - name: Clean & packages
        script: |
          flutter clean
          flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..

      - name: Set up signing
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa \
            --release \
            --export-method app-store \
            --no-codesign

      - name: Export signed IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner

    artifacts:
      - build/ios/ipa/*.ipa